### ISSUE TITLE
bug: 在更新"$:/plugins/linonetwo/itonnote"后丢失“TiddlyWiki-CPL”

### ISSUE THREAD

**Issue by wwhiffle** [tiddly-gittly/itonnote-plugin#10]
## Environment 环境信息

- 操作系统: Windows 10 专业工作站版 22H2
- TidGi-Desktop: v0.8.1-prerelease6

## Description 描述

在Windows最新版“TidGi-Desktop”中，当我尝试更新“$:/plugins/linonetwo/itonnote”到最新版本时，我发现“TiddlyWiki-CPL”会被丢失。在没有这个bug的情况下，“TiddlyWiki-CPL”应该仍然存在并可以正常使用。

## Steps to Reproduce 复现方式

1. 在Windows最新版的“TidGi-Desktop”上新建一个wiki。
2. 此时检查，可以发现“TiddlyWiki-CPL”正常存在。
3. 更新插件“$:/plugins/linonetwo/itonnote”到最新版本。
4. 重启服务。
5. 此时会发现“TiddlyWiki-CPL”已经被丢失。
![2023-09-14_00001](https://github.com/tiddly-gittly/itonnote-plugin/assets/100055123/a9bf5f55-f0c6-487c-8c56-0cecb6ffb712)

## Additional Context 额外上下文

这个问题对于那些依赖“TiddlyWiki-CPL”来查找和管理插件的用户来说可能会造成很大的困扰。如果需要更多的日志或信息，请告知。

**Comment by linonetwo** [comment]
参考 [插件更新后重启又要更新](https://tw-cn.netlify.app/#%E6%8F%92%E4%BB%B6%E6%9B%B4%E6%96%B0%E5%90%8E%E9%87%8D%E5%90%AF%E5%8F%88%E8%A6%81%E6%9B%B4%E6%96%B0) 删掉  $__plugins_linonetwo_itonnote.json.meta 即可修复

https://github.com/Jermolene/TiddlyWiki5/issues/7741
