### ISSUE TITLE
更新依赖安装

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/itonnote-plugin#9]
![image](https://github.com/tiddly-gittly/itonnote-plugin/assets/109711900/1c276ef1-fda6-492b-8976-e0b9111cf329)

![image](https://github.com/tiddly-gittly/itonnote-plugin/assets/109711900/78226a19-50a3-49af-98b8-b614baba7568)

配置出问题了。

**Comment by linonetwo** [comment]
<img width="374" alt="截屏2023-07-12 23 13 02" src="https://github.com/tiddly-gittly/itonnote-plugin/assets/3746270/11ef6a25-c13e-44ba-8319-5a09a1620f8f">

配阿里源

**Comment by dongrentianyu** [comment]
配置了，但失败了。

`RequestError: connect ETIMEDOUT 20.205.243.166:443`

基本上就是上面的报错提示。明天再看看。

**Comment by dongrentianyu** [comment]
或者就是`RequestError: read ECONNRESET`

**Comment by dongrentianyu** [comment]
我感觉这网络问题是阻碍开发的一个前置问题啊。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/itonnote-plugin/assets/109711900/76c9abd6-6b20-45ea-9130-753f35e2ffb0)

还没完全成功，不知道我搞错了什么。

**Comment by linonetwo** [comment]
不知道，可能Windows下有bug，之前遇到这种问题，我都会把旧的代码拷出来转换成modern框架的写法，他那个支持Windows比较好。

**Comment by dongrentianyu** [comment]
这个能更新成modern框架吗？感觉这不好解决啊。

**Comment by linonetwo** [comment]
都能，类似 https://github.com/tiddly-gittly/in-tagtree-of/commit/b3fa7d98cd8abb8d2701bc05b20f7072cdfaeb6a

其实就是把 demo/ 变成 wiki/  src/ 变成 src/插件名/ 等等，然后别的大都删了直接用 modern cli 生成的

**Comment by linonetwo** [comment]
我最近没空改，有空再看看，最终都要迁移过去的

**Comment by dongrentianyu** [comment]
嗯，还是等你迁移好了，我再处理吧。我看要改动的内容还挺多的，就不自己去改了。

**Comment by linonetwo** [comment]
这个现在完全没问题了
